-- Specify the role and compute resource
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

-- Create a databse for Project-2 DBT GLUE - P1_DB
CREATE OR REPLACE DATABASE PP1_WMRT;

-- Create the storage integration with S3 with previously created S3 ARN and IAM role
CREATE OR REPLACE STORAGE INTEGRATION S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = '<AWS_IAM_ROLE_ARN>'
  STORAGE_ALLOWED_LOCATIONS = ('s3://<BUCKET_NAME>/raw_data/')


  -- Get the AWS IAM USER ARN and External ID to update the AWS IAM P1-SnowPipeRole
DESC INTEGRATION S3_INT;

-- Create a staging location using the SI
CREATE OR REPLACE STAGE PP1_WMRT.PUBLIC.S3_STAGE
STORAGE_INTEGRATION = S3_INT
URL = 's3://<BUCKET_NAME>/raw_data/';

-- Validate the SI is working properly
ls @PP1_WMRT.PUBLIC.S3_STAGE;

-- Use this database for the rest of the project
USE DATABASE PP1_WMRT;

-- Create schemas needed
CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA MARTS;

-- Create CSV file format
CREATE OR REPLACE FILE FORMAT PP1_WMRT.PUBLIC.CSV_FILE_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
NULL_IF = ('NULL','NA');

-- Create raw table - 'STORES_RAW'
CREATE OR REPLACE TABLE PP1_WMRT.RAW.WALMART_STORES_RAW
(
    STORE_ID      INTEGER,
    STORE_TYPE    VARCHAR(20),
    STORE_SIZE    INTEGER
);

-- Create raw table - 'DEPARTMENT_RAW'
CREATE OR REPLACE TABLE PP1_WMRT.RAW.WALMART_DEPARTMENT_RAW
(
    STORE_ID          INTEGER,
    DEPT_ID           INTEGER,
    DATE              DATE,
    WEEKLY_SALES      NUMBER(18,2),
    ISHOLIDAY         BOOLEAN
);

-- Create raw table - 'FACT_RAW'
CREATE OR REPLACE TABLE PP1_WMRT.RAW.WALMART_FACT_RAW
(
    STORE_ID         INTEGER,
    DATE             DATE,
    TEMPERATURE      NUMBER(8,2),
    FUEL_PRICE       NUMBER(8,2),
    MARKDOWN1        NUMBER(18,2),
    MARKDOWN2        NUMBER(18,2),
    MARKDOWN3        NUMBER(18,2),
    MARKDOWN4        NUMBER(18,2),
    MARKDOWN5        NUMBER(18,2),
    CPI              NUMBER(10,2),
    UNEMPLOYMENT     NUMBER(8,2),
    ISHOLIDAY        BOOLEAN
);

-- Load raw data into STORES_RAW
COPY INTO PP1_WMRT.RAW.WALMART_STORES_RAW
FROM @PP1_WMRT.PUBLIC.S3_STAGE/stores.csv
FILE_FORMAT = (FORMAT_NAME = PP1_WMRT.PUBLIC.CSV_FILE_FORMAT);

-- Load raw data into DEPARTMENT_RAW
COPY INTO PP1_WMRT.RAW.WALMART_DEPARTMENT_RAW
FROM @PP1_WMRT.PUBLIC.S3_STAGE/department.csv
FILE_FORMAT = (FORMAT_NAME = PP1_WMRT.PUBLIC.CSV_FILE_FORMAT);

-- Load raw data into FACT_RAW
COPY INTO PP1_WMRT.RAW.WALMART_FACT_RAW
FROM @PP1_WMRT.PUBLIC.S3_STAGE/fact.csv
FILE_FORMAT = (FORMAT_NAME = PP1_WMRT.PUBLIC.CSV_FILE_FORMAT);

select * from PP1_WMRT.RAW.WALMART_DEPARTMENT_RAW;
