select
    {{ surrogate_key(['store_week_key', 'dbt_valid_from']) }} as store_week_version_key,
    store_week_key,
    store_id,
    cast(to_char(week_date, 'YYYYMMDD') as integer) as date_id,
    temperature,
    fuel_price,
    markdown_1,
    markdown_2,
    markdown_3,
    markdown_4,
    markdown_5,
    cpi,
    unemployment,
    is_holiday,
    dbt_valid_from as vrsn_start_date,
    coalesce(dbt_valid_to, cast('9999-12-31 23:59:59' as timestamp)) as vrsn_end_date,
    dbt_valid_to is null as is_current,
    dbt_valid_from as insert_date,
    coalesce(dbt_valid_to, dbt_valid_from) as update_date
from {{ ref('snap_store_weekly_features') }}
